name: deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hello-world:$GITHUB_RUN_ID

  deploy:
    runs-on: ubuntu-latest
    needs: [build-docker]
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
          # this explicitly ensures that the AWS account ID does not get leaked into logs
          mask-aws-account-id: true
        
      - name: Deploy Fargate stack to CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: fargate-stack
          template: cf/deploy-fargate.yml
          parameter-overrides: "ImageUrl=${{ secrets.DOCKER_HUB_USERNAME }}/hello-world:latest"
          no-fail-on-empty-changeset: 1
